version: '3.6'

services:
  postgres:
    image: 'postgres:11-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
